/* Copyright © 2006 Nokia. */
// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package com.nokia.midp.examples.webservices;
/**
 * A generated stub
 * */
public interface CapitalPortType extends java.rmi.Remote {
	public java.lang.String getCapital(java.lang.String nation) throws java.rmi.RemoteException;

}
